### PR TITLE
improve support for namespaced models

### PR DESCRIPTION
**Pull request by ghost**
slight tweaks to how model files are found and loaded

### CODE REVIEW

**Comment by preston** [comment]
Is this something we might want to merge in upstream?

**Comment by ghost** [comment]
@preston this may have been solved by preston/railroady#80; I'll take a look and open a new PR upstream if necessary.

**Comment by preston** [comment]
@BM5k Right on, thanks! It sounds like @adarr may be looking for the same thing on https://github.com/preston/railroady/issues/86

**Comment by ghost** [comment]
closed & reopening upstream

**Pull request closed without merging**
